version: '3.9'

services:
  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:14-alpine
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      # POSTGRES_HOST: postgres
      # POSTGRES_USER: sally
      # POSTGRES_PASSWORD: secret
      # POSTGRES_DB: smart-brain-docker
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
    # container_name: postgres  # error would occur
    # image: postgres
    build: postgres
    ports:
      - '5432:5432'

  # Redis
  redis:
    image: redis
    ports:
      - '6379:6379'
