version: 2.1
jobs:
  bobby:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run: echo "A first hello"
  sally:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run: echo "Double trouble"
workflows:
  version: 2.1
  bobby_sally:
    jobs:
      - bobby
      - sally
